services:
  development:
    build:
      context: .
      dockerfile: Dockerfile
      target: development # Use the 'development' stage from Dockerfile for development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm run dev

  qa:
    image: ghcr.io/luden-labs-ltd/enola_dashboard-next-js:qa-latest
    # build:
      # context: .
      # dockerfile: Dockerfile
      # target: production # Use the 'production' stage from Dockerfile for production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=16384
      - BUILD_STANDALONE='true'
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-c", "nc -z $(hostname -i) 3000"]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3

  production:
    build:
      context: .
      dockerfile: Dockerfile
      target: production # Use the 'production' stage from Dockerfile for production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=16384
      - BUILD_STANDALONE='true'
    env_file:
      - .env.production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-c", "nc -z $(hostname -i) 3000"]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3
